# Generated by Django 5.2.8 on 2025-11-11 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송 시각')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='수신 확인 시각')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='발신자')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['sender'], name='communicati_sender__822f5c_idx'), models.Index(fields=['recipient'], name='communicati_recipie_0c742b_idx'), models.Index(fields=['sender', 'recipient'], name='communicati_sender__9f3776_idx')],
            },
        ),
    ]
