# Generated by Django 5.2.8 on 2025-11-11 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.lecture', verbose_name='관련 강의'),
        ),
    ]
