# Generated by Django 5.2.8 on 2025-11-11 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='강의명')),
                ('type', models.CharField(blank=True, choices=[('general', '일반 (노랑)'), ('competition', '대회 (하늘)'), ('camp', '캠프 (연두)'), ('totoland', '도로랜드 (파랑)'), ('booth', '부스 (핑크)'), ('etc', '기타 (회색)')], max_length=20, null=True, verbose_name='강의 유형')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='강의 구분')),
                ('status', models.CharField(choices=[('recruiting', '모집중'), ('allocating', '배정 중'), ('completed', '배정 완료')], default='recruiting', max_length=20, verbose_name='강의 상태')),
                ('lecture_start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='강의 시작 일시')),
                ('lecture_end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='강의 종료 일시')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='강의 장소')),
                ('target_audience', models.CharField(blank=True, max_length=100, null=True, verbose_name='교육 대상')),
                ('content_description', models.TextField(blank=True, null=True, verbose_name='콘텐츠 설명')),
                ('special_notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='특이사항')),
                ('attachment_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='첨부파일 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_lectures', to=settings.AUTH_USER_MODEL, verbose_name='담당 매니저')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LectureRecruitment',
            fields=[
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recruitment_info', serialize=False, to='lectures.lecture', verbose_name='강의')),
                ('application_start_date', models.DateField(blank=True, null=True, verbose_name='강사 모집 시작일')),
                ('application_end_date', models.DateField(blank=True, null=True, verbose_name='강사 모집 마감일')),
                ('max_participants', models.IntegerField(blank=True, null=True, verbose_name='모집 인원')),
                ('recruitment_main_needed', models.IntegerField(default=0, verbose_name='필요한 주강사 수')),
                ('recruitment_assist_needed', models.IntegerField(default=0, verbose_name='필요한 보조강사 수')),
                ('fee_main', models.IntegerField(blank=True, null=True, verbose_name='주강사 강의료')),
                ('fee_assist', models.IntegerField(blank=True, null=True, verbose_name='보조강사 강의료')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_role', models.CharField(choices=[('main', '주도로맨 (주강사)'), ('assist', '보조도로맨 (보조강사)')], max_length=10, verbose_name='지원 역할')),
                ('portfolio_snapshot', models.TextField(blank=True, help_text='지원 시점의 user.portfolio_content를 복사하여 저장', null=True, verbose_name='지원 시점 포트폴리오')),
                ('assignment_status', models.CharField(choices=[('pending', '미배정'), ('assigned', '배정완료'), ('rejected', '배정 실패')], default='pending', max_length=10, verbose_name='배정 상태')),
                ('assigned_role', models.CharField(blank=True, choices=[('main', '주도로맨 (주강사)'), ('assist', '보조도로맨 (보조강사)')], max_length=10, null=True, verbose_name='최종 배정된 역할')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='지원 일시')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='지원 강사')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='lectures.lecture', verbose_name='지원 강의')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['manager'], name='lectures_le_manager_ef215b_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['status'], name='lectures_le_status_5137b6_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['type'], name='lectures_le_type_ae34b7_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['lecture_start_datetime'], name='lectures_le_lecture_9c8486_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user'], name='lectures_ap_user_id_620acc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('lecture', 'user', 'applied_role')},
        ),
    ]
